import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import Drawer from "@/components/Drawer";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Tienda Calazns",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="flex max-lg:flex-col">
          <Drawer />

          <div className="bg-base-100 flex flex-col w-full p-8">
            <div className="w-full h-full box-border border-black border-2 rounded-md p-4">
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
